### ISSUE TITLE
Support remove schema dynamically

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere-ui#43]
For the second module `Remove schemas in sharding-ui` of issue apache/shardingsphere#5043 , there are 3 steps: 

- [x] 1. Add `delete(key)` interface in `CenterRepository`  and implement it with zookeeper&etcd&nacos&apollo(#5101)
- [x] 2. Add unit tests(#5101)
- [x] 3. Add a button to remove schemas in sharding-ui(#5112)
